apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timelog2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timelog2
  template:
    metadata:
      labels:
        app: timelog2
        editor: vscode
    spec:
      containers:
      - name: michalp96/timelog2
        image: michalp96/timelog2:latest
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: timelog2
spec:
  selector:
    app: timelog2
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000 
  type: LoadBalancer  